import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/auth"
import { redirect } from "next/navigation"
import { CsvUploader } from "@/components/dashboard/admin/csv-uploader"
import { importUsersCsv, importCoursesCsv, importSectionsCsv, importEnrollmentsCsv } from "@/app/actions/imports"

export const metadata = { title: "Data Ingestion | Schoolyard" }

export default async function AdminImportsPage() {
  const session = await getServerSession(authOptions)
  if (!session || session.user?.role !== "ADMIN") redirect("/dashboard")

  return (
    <div className="p-6 md:p-8 max-w-5xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Data Ingestion Hub</h1>
        <p className="text-slate-500 mt-1">Bulk upload CSV data to populate the SIS infrastructure.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <CsvUploader 
          title="1. Users & Roster" 
          description="Create Student, Teacher, and Admin accounts. New accounts receive a default password."
          expectedHeaders={["Email", "Name", "Role", "Department"]}
          action={importUsersCsv}
        />

        <CsvUploader 
          title="2. Course Catalog" 
          description="Define the universal course catalog and credit values."
          expectedHeaders={["Code", "Name", "Credits", "Description"]}
          action={importCoursesCsv}
        />

        <CsvUploader 
          title="3. Master Schedule (Sections)" 
          description="Build out sections by linking Courses to Teachers and Terms."
          expectedHeaders={["CourseCode", "TeacherEmail", "TermID", "Schedule", "Room"]}
          action={importSectionsCsv}
        />

        <CsvUploader 
          title="4. Mass Enrollments" 
          description="Enroll students into specific sections in bulk."
          expectedHeaders={["StudentEmail", "SectionID"]}
          action={importEnrollmentsCsv}
        />
      </div>

      <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 p-5 rounded-xl">
        <h3 className="font-bold text-amber-800 dark:text-amber-500 flex items-center gap-2">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          Important Ingestion Notes
        </h3>
        <ul className="list-disc list-inside mt-3 text-sm text-amber-700 dark:text-amber-600 space-y-1">
          <li>Always follow the ingestion order (Users &rarr; Courses &rarr; Sections &rarr; Enrollments) to prevent relational errors.</li>
          <li>For TermID in the Master Schedule upload, use the exact internal Term ID generated by the system, which you can find in the Calendar Setup page.</li>
          <li>For SectionID in Enrollments, use the internal Section ID.</li>
          <li>The system uses Upsert logic for Users and Courses; uploading existing records will update them rather than duplicate them.</li>
        </ul>
      </div>
    </div>
  )
}
